[package]
name = "spinning-cube"
version = "0.1.0"
authors = ["The godot-rust developers"]
edition = "2021"
rust-version = "1.63"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
gdnative = { path = "../../gdnative" }
